name: ci
on:
  pull_request:

jobs:
  rpmbuild-rocky8:
    name: rpmbuild-rocky8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # fetch tags as checkout@v2 doesn't do that by default
      - run: git fetch --prune --unshallow --tags --force

      - name: Build rpm under docker
        env:
          OS_TYPE: rockylinux
          OS_VERSION: 8
        run: ./ci/docker-run
